---
#Currently working on:
  # 1. Update DNS to automatically point to new servers

Parameters: 
  UserPassword: 
    Type: String
    NoEcho: true
    Description: Enter a password for the masteruser

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: True
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: servianappdb
      DBName: 'app'
      Engine: postgres
      EngineVersion: '12.3'
      MasterUsername: 'postgres'
      MasterUserPassword: !Ref UserPassword
      MultiAZ: True
      PubliclyAccessible: True
      VPCSecurityGroups: 
        - sg-089475c14977a0c5b
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 'ami-0810abbfb78d37cdf'
      InstanceType: 't2.micro'
      KeyName: servian-app-challenge
      SecurityGroupIds: 
        - sg-09ab03ff4eea2e604
      SubnetId: subnet-a95be4f1
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash 
            sudo su -

            useradd service-user
            echo ${UserPassword} | passwd --stdin service-user
            echo 'service-user   ALL=(ALL)  ALL' >> /etc/sudoers
            sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            service sshd restart

            yum update -y
            mkdir /home/TechChallenge/
            cd /home/TechChallenge/
            yum install git -y
            yum install go -y
            git clone https://github.com/servian/TechChallengeApp.git
            cd TechChallengeApp
            ./build.sh
            cd dist/
            sed -i 's/^"DbPassword" = "changeme"/"DbPassword" = "${UserPassword}"/g' /home/TechChallenge/TechChallengeApp/dist/conf.toml
            sed -i 's/^"DbHost" = "localhost"/"DbHost" = "servianappdb.nicholasyee.net"/g' /home/TechChallenge/TechChallengeApp/dist/conf.toml
            sed -i 's/^"ListenHost" = "localhost"/"ListenHost" = "0.0.0.0"/g' /home/TechChallenge/TechChallengeApp/dist/conf.toml
            sed -i 's/^"ListenPort" = "3000"/"ListenPort" = "80"/g' /home/TechChallenge/TechChallengeApp/dist/conf.toml
            
            ./TechChallengeApp updatedb
            ./TechChallengeApp serve